import "./globals.css";
import Nav from "./Components/Nav";
import Patients from "./Components/Patients";
import { manrope } from "./fonts/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
      {/* <body className={manrope.variable}> */}
        <div className="md:px-4">
          <Nav />
          <div className="flex flex-row">
            <Patients />
            <div className="flex flex-col flex-1">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
